# Lab2. Design of Logic Gates using Perceptron and Keras

## Part-I: Design OR gate using the concept of Perceptron

### Step1: Define helper functions

In [1]:
import numpy as np
import math

In [2]:
def sigmoid(x):
    s=1/(1+math.exp(-x))
    return s

In [3]:
def logic_gate(w1,w2,b):
    return lambda x1,x2: sigmoid(w1*x1+w2*x2+b)

In [4]:
def test(gate):
    for a,b in (0,0),(0,1),(1,0),(1,1):
        print("{},{}: {}".format(a,b,np.round(gate(a,b))))

### Step2: 
Identify values for weights, w1 and w2 and bias, b, for OR gate.
Then, call logic_gate() function first with the values of weights and bias and
test the outputs. For example, do the following steps and verify OR gate
operations.

In [5]:
or_gate = logic_gate(20, 20, -10)
test(or_gate)

0,0: 0.0
0,1: 1.0
1,0: 1.0
1,1: 1.0


## Part-II: Implement the operations of AND, NOR and NAND gates

### Step1: 
Identify values for weights, w1 and w2 and bias, b, for AND gate.
Then, call logic_gate() function first with the values of weights and bias and
test the outputs. Draw manually using pen the diagram of OR gate.

In [6]:
and_gate = logic_gate(10, 10, -10)
test(and_gate)

0,0: 0.0
0,1: 0.0
1,0: 0.0
1,1: 1.0


### Step2: 
Identify values for weights, w1 and w2 and bias, b, for NOR gate.
Then, call logic_gate() function first with the values of weights and bias and
test the outputs. Draw manually using pen the diagram of NOR gate.

In [7]:
nor_gate = logic_gate(-20,-20,10)
test(nor_gate)

0,0: 1.0
0,1: 0.0
1,0: 0.0
1,1: 0.0


### Step3:
Identify values for weights, w1 and w2 and bias, b, for NAND gate.
Then, call logic_gate() function first with the values of weights and bias and
test the outputs. Draw manually using pen the diagram of NAND gate.

In [8]:
nand_gate = logic_gate(-1,-1,2)
test(nand_gate)

0,0: 1.0
0,1: 1.0
1,0: 1.0
1,1: 0.0


## Part-III: Limitations of single neuron for XOR operation

Can you identify a set of weights such that a single neuron can output the
values for XOR gate?. Single neurons can't correlate inputs, so it's just
confused. So individual neurons are out. Can we still use neurons to
somehow form an XOR gate?.

In [9]:
def xor_gate(a,b):
    c=or_gate(a,b)
    d=nand_gate(a,b)
    return and_gate(c,d)
test(xor_gate)

0,0: 0.0
0,1: 1.0
1,0: 1.0
1,1: 1.0


In [10]:
def logic_gate(w1, W2, b):
    return lambda x1, x2: sigmoid(w1 * x1 + W2 * x2 + b)
def final(gate):
    for a, b in zip(result1, result2):
        print("{}, {}: {}".format(a, b, np.round(gate(a, b))))

result1 = []
result2 = []

or_gate = logic_gate(20,20,-10)
for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
    result1.append(np.round(or_gate(a,b)))

nand_gate = logic_gate(-23,-25,35)
for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
    result2.append(np.round(nand_gate(a,b)))

xor_gate = logic_gate(20,20,-30)

print("XOR Gate truth table \n")
print("X, Y X+Y")
final(xor_gate) 

XOR Gate truth table 

X, Y X+Y
0.0, 1.0: 0.0
1.0, 1.0: 1.0
1.0, 1.0: 1.0
1.0, 0.0: 0.0


## Part-IV: Logic Gates using Keras library
In this part of the lab, you will create and implement the operations of logic
gates such as AND, OR, NOT, NAND, NOR and XOR in Keras.

In [11]:
from keras.models import Sequential
from keras.layers.core import Dense

In [12]:
#AND gate
# the four different states of the AND gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

# the four expected results in the same order
target_data = np.array([[0],[0],[0],[1]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)

print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.2656 - binary_accuracy: 0.7500 - 360ms/epoch - 360ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2650 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2644 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2638 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2632 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2627 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2621 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2615 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2609 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2604 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2598 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2592 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.2187 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2182 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2177 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2173 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
[[0.]
 [0.]
 [0.]
 [0.]]


In [13]:
#OR gate
# the four different states of the OR gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

# the four expected results in the same order
target_data = np.array([[0],[1],[1],[1]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)

print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.4085 - binary_accuracy: 0.2500 - 240ms/epoch - 240ms/step
Epoch 2/100
1/1 - 0s - loss: 0.4068 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 3/100
1/1 - 0s - loss: 0.4051 - binary_accuracy: 0.0000e+00 - 2ms/epoch - 2ms/step
Epoch 4/100
1/1 - 0s - loss: 0.4035 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 5/100
1/1 - 0s - loss: 0.4018 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 6/100
1/1 - 0s - loss: 0.4002 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.3985 - binary_accuracy: 0.0000e+00 - 996us/epoch - 996us/step
Epoch 8/100
1/1 - 0s - loss: 0.3969 - binary_accuracy: 0.0000e+00 - 2ms/epoch - 2ms/step
Epoch 9/100
1/1 - 0s - loss: 0.3952 - binary_accuracy: 0.0000e+00 - 4ms/epoch - 4ms/step
Epoch 10/100
1/1 - 0s - loss: 0.3936 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.3919 - binary_accuracy: 0.0000e+00 - 2ms/epoch - 2ms/step
Epoch 12/100
1/

Epoch 93/100
1/1 - 0s - loss: 0.2822 - binary_accuracy: 0.2500 - 3ms/epoch - 3ms/step
Epoch 94/100
1/1 - 0s - loss: 0.2812 - binary_accuracy: 0.2500 - 2ms/epoch - 2ms/step
Epoch 95/100
1/1 - 0s - loss: 0.2801 - binary_accuracy: 0.2500 - 2ms/epoch - 2ms/step
Epoch 96/100
1/1 - 0s - loss: 0.2791 - binary_accuracy: 0.2500 - 4ms/epoch - 4ms/step
Epoch 97/100
1/1 - 0s - loss: 0.2780 - binary_accuracy: 0.2500 - 3ms/epoch - 3ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2770 - binary_accuracy: 0.2500 - 2ms/epoch - 2ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2759 - binary_accuracy: 0.2500 - 2ms/epoch - 2ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2749 - binary_accuracy: 0.2500 - 4ms/epoch - 4ms/step
[[1.]
 [0.]
 [1.]
 [0.]]


In [13]:
#NOT gate
# the four different states of the NOT gate
training_data = np.array([[0],[1]], "float32")

# the four expected results in the same order
target_data = np.array([[1],[0]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=1, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)

print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.2739 - binary_accuracy: 0.0000e+00 - 199ms/epoch - 199ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2730 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2722 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2713 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2705 - binary_accuracy: 0.0000e+00 - 4ms/epoch - 4ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2697 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2689 - binary_accuracy: 0.0000e+00 - 4ms/epoch - 4ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2680 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2672 - binary_accuracy: 0.0000e+00 - 12ms/epoch - 12ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2664 - binary_accuracy: 0.0000e+00 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2656 - binary_accuracy: 0.0000e+00 - 4ms/epoch - 4ms/step
Epoch 12/100


1/1 - 0s - loss: 0.2221 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 96/100
1/1 - 0s - loss: 0.2217 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 97/100
1/1 - 0s - loss: 0.2212 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2207 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2203 - binary_accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2198 - binary_accuracy: 1.0000 - 4ms/epoch - 4ms/step
[[1.]
 [0.]]


In [14]:
#NAND gate
# the four different states of the NAND gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

# the four expected results in the same order
target_data = np.array([[1],[1],[1],[0]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)

print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.2398 - binary_accuracy: 0.5000 - 194ms/epoch - 194ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2392 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2385 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2378 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2371 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2364 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2358 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2351 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2344 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2337 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2331 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2324 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.1778 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1771 - binary_accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1765 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1758 - binary_accuracy: 1.0000 - 4ms/epoch - 4ms/step
[[1.]
 [1.]
 [1.]
 [0.]]


In [15]:
#NOR gate
# the four different states of the NOR gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

# the four expected results in the same order
target_data = np.array([[1],[0],[0],[0]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)

print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.1981 - binary_accuracy: 0.7500 - 191ms/epoch - 191ms/step
Epoch 2/100
1/1 - 0s - loss: 0.1970 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 3/100
1/1 - 0s - loss: 0.1958 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 4/100
1/1 - 0s - loss: 0.1946 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 5/100
1/1 - 0s - loss: 0.1935 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 6/100
1/1 - 0s - loss: 0.1923 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 7/100
1/1 - 0s - loss: 0.1912 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 8/100
1/1 - 0s - loss: 0.1901 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 9/100
1/1 - 0s - loss: 0.1890 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 10/100
1/1 - 0s - loss: 0.1879 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 11/100
1/1 - 0s - loss: 0.1868 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 12/100
1/1 - 0s - loss: 0.1857 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.1287 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1284 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1280 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1277 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
[[0.]
 [0.]
 [0.]
 [0.]]


In [16]:
#XOR gate
# the four different states of the XOR gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

# the four expected results in the same order
target_data = np.array([[0],[1],[1],[0]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)

print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.2461 - binary_accuracy: 0.7500 - 197ms/epoch - 197ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2458 - binary_accuracy: 0.5000 - 2ms/epoch - 2ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2454 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2450 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2447 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2443 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2440 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2436 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2432 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2428 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2425 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2421 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.2231 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2229 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2227 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2224 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
[[0.]
 [0.]
 [1.]
 [0.]]
